---
- name: check for connection server
  win_stat:
    path: 'C:\Program Files\VMware\VMware View\Server\bin\ws_ConnectionServer.exe'
  register: connection_info

- name: check for connection server version
  win_file_version:
    path: 'C:\Program Files\VMware\VMware View\Server\bin\ws_ConnectionServer.exe'
  register: exe_file_version

#TODO: some sort of error checking against installed versus new
- debug:
    msg: 'Found version {{ exe_file_version.win_file_version.product_version }} connection server, upgrading...'

- name: remove all snapshots
  vmware_guest_snapshot:
    hostname: "{{ vsphere_server }}"
    password: "{{ vsphere_password }}"
    datacenter: "{{ vsphere_dc_name }}"
    folder: "/{{ vsphere_dc_name }}/{{ vsphere_folder }}/"
    name: "{{ ansible_facts['hostname'] }}"
    state: remove_all
  delegate_to: localhost

- name: create snapshot
  vmware_guest_snapshot:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    datacenter: "{{ vsphere_dc_name }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ ansible_facts['hostname'] }}"
    state: present
    snapshot_name: "Ansible Managed Snapshot"
    folder: "/{{ vsphere_dc_name }}/{{ vsphere_folder }}/"
    description: "This snapshot is created by Ansible Playbook before upgrading Connection Server from {{ exe_file_version.win_file_version.product_version }}"
  delegate_to: localhost

#2022-12-24T06:30:48.356Z INFO  (09B4-04A4) <1188> [ws_ldap] LDAP Backup Service completed command for LDAP backup to C:\ProgramData\VMware\VDM\backups successfully
# C:\Program Files\VMware\VMware View\Server\tools\bin>vdmexport -f C:\Install\Backup.LDF
# C:\Program Files\VMware\VMware View\Server\tools\bin>vdmimport -d -p Password1234 -f C:\Install\Backup.LDF > C:\Install\BackupDecryptedExport.LDF