variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "PDC_IP" {}
variable "PDC_cpu_num" {}
variable "PDC_mem" {}
variable "netmask" {}
variable "def_gw" {}
variable "dns_server" {}
variable "ConnServ1_name" {}
variable "ConnServ1_IP" {}
variable "ConnServ1_cpu_num" {}
variable "ConnServ1_mem" {}
variable "ConnServ2_name" {}
variable "ConnServ2_IP" {}
variable "ConnServ2_cpu_num" {}
variable "ConnServ2_mem" {}
variable "ConnServ3_name" {}
variable "ConnServ3_IP" {}
variable "ConnServ3_cpu_num" {}
variable "ConnServ3_mem" {}
variable "firmware" {}
