---
- name: check for connection server
  win_stat:
    path: 'C:\Program Files\VMware\VMware View\Server\bin\ws_ConnectionServer.exe'
  register: connection_info

- name: create a folder for installers
  win_file:
    path: "{{ install_folder }}"
    state: directory
  when: connection_info.stat.exists == False

- name: download connection server installer
  win_get_url:
    url: "{{ install_url }}"
    dest: "{{ install_binary_dest }}"
  when: connection_info.stat.exists == False

# TODO: Parameterize this
# bandaid to get hz_admin group sid VDM_INITIAL_ADMIN_SID=
- name: install connection server
  win_command: C:\Install\VMware-Horizon-Connection-Server-x86_64-8.7.0-20649599.exe /s /v" /qn FWCHOICE=1 VDM_SERVER_INSTANCE_TYPE=1 HTMLACCESS=1 VDM_INITIAL_ADMIN_SID="{{lookup('ansible.builtin.file', '/home/vagrant/github/windows_lab/ansible/bandaid.txt') }}" VDM_SERVER_RECOVERY_PWD="Password1234" VDM_SERVER_RECOVERY_PWD_REMINDER="nothing""
  become: yes
  become_method: runas
  become_user: "{{ hz_admin_user_domain }}"
  vars:
    ansible_become_password: "{{ hz_admin_pass }}"
  when: connection_info.stat.exists == False

- name: check for connection server
  win_stat:
    path: 'C:\Program Files\VMware\VMware View\Server\bin\ws_ConnectionServer.exe'
  register: connection_info_after

- name: reboot after connect server installed
  win_reboot:
    msg: "Installing VMware Horizon Connection Server. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 900
    post_reboot_delay: 600
  when: (connection_info.stat.exists == False and connection_info_after.stat.exists == True)
