---
- name: create Horizon admin group
  ansible.windows.win_group:
    name: hz_admin
    description: Horizon Admins
    state: present

- name: install nuget packge for OU creation
  win_shell: install-packageprovider -name nuget -force

- name: install XactiveDirectory package for OU creation
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present

- name: create OU for admins
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Admins"
    path: "dc={{ netbios_domain }}, dc={{ top_level_domain }}"

- name: create Horizon admin user
  community.windows.win_domain_user:
    name: horizonadmin
    firstname: horizon
    surname: admin
    password: Password1234
    state: present
    path: "ou=Admins, dc={{ netbios_domain }}, dc={{ top_level_domain }}"
    groups: 
    - Domain Users
    - hz_admin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
