---
- name: create Horizon admin group
  win_domain_group:
    name: hz_admin
    scope: domainlocal
    category: security
    attributes:
      mail: helpdesk@ansible.com
      wWWHomePage: www.ansible.com

- name: install nuget packge for OU creation
  win_shell: install-packageprovider -name nuget -force

- name: install XactiveDirectory package for OU creation
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present

- name: create OU for admins
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Admins"
    path: "dc={{ netbios_domain }}, dc={{ top_level_domain }}"

- name: create Horizon admin user
  community.windows.win_domain_user:
    name: horizonadmin
    firstname: horizon
    surname: admin
    password: Password1234
    state: present
    path: "ou=Admins, dc={{ netbios_domain }}, dc={{ top_level_domain }}"
    groups: 
    - Domain Users
    - hz_admin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

# start bandaid for hz_admin user sid required for connection server install
# wouldn't be a problem if AD already existed and sid was just a normal parameter
- name: get the sid for hz_admin group
  community.windows.win_domain_object_info:
    ldap_filter: (&(objectCategory=group)(name=hz_admin))
    properties:
    - objectSid
  register: admin_group

- name: put the sid in the contents of a file
  ansible.builtin.copy:
    content: "{{ admin_group.objects[0].objectSid.Sid }}"
    dest: 'C:\bandaid.txt'

- name: fetch the file containing the sid
  fetch: src=C:/bandaid.txt dest=~/github/windows_lab/ansible/bandaid.txt flat=yes
