---
- name: remove all snapshots
  vmware_guest_snapshot:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    datacenter: "{{ vsphere_dc_name }}"
    folder: "/{{ vsphere_dc_name }}/{{ vsphere_folder }}/"
    name: "{{ ansible_facts['hostname'] }}"
    state: remove_all
  delegate_to: localhost

- name: create snapshot
  vmware_guest_snapshot:
    hostname: "{{ vsphere_server }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    datacenter: "{{ vsphere_dc_name }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ ansible_facts['hostname'] }}"
    state: present
    snapshot_name: "Ansible Managed Snapshot"
    folder: "/{{ vsphere_dc_name }}/{{ vsphere_folder }}/"
    description: "This snapshot is created by Ansible Playbook before running any installs"
  delegate_to: localhost

- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - "{{ groups['pdc'][0] }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ ansible_facts['nodename'] }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
    msg: "ansible just added me to the domain... Rebooting..."
    pre_reboot_delay: 15
  when: domain_joined.reboot_required

- name: add hz_admin group to local admin
  win_group_membership:
    name: Administrators
    members:
      - windows_lab\hz_admin
    state: present

- include: connection_server_standard.yml
