---
- hosts: pdc
  roles:
    - pdc
    - pdc_userdata
    - common
    
- hosts: cs
  roles:
    - connection_server_standard_install
    - common

- hosts: csr
  roles:
    - connection_server_replica_install
    - common
