---
# - name: checking for powercli module
#   win_shell: Import-Module -Name VMware.PowerCLI
#   register: _powercli_module
#   failed_when: false
#   changed_when: false

# - name: install powercli module
#   win_shell: Install-Module -Name VMware.PowerCLI –Force
#   when: _powercli_module['rc'] != 0

# - name: manage powercli customer experience improvement program
#   win_shell: "Set-PowerCLIConfiguration -ParticipateInCeip $false -confirm:$false"
#   when: _powercli_module['rc'] != 0
  
# - name: checking for horizon module
#   win_shell: Import-Module -Name VMware.VimAutomation.HorizonView -DisableNameChecking
#   register: _horizon_module
#   failed_when: false
#   changed_when: false

# - name: install horizon module
#   win_shell: Install-Module -Name VMware.VimAutomation.HorizonView –Force
#   when: _horizon_module['rc'] != 0
#   register: install_result

# - name: disable ssl certificate checking
#   win_shell: |
#     Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false
#   when: install_result is changed

# - name: create location for HV.Helper modules
#   win_file:
#     path: 'C:\Program Files\WindowsPowerShell\Modules\VMware.HV.Helper\'
#     state: directory
#   when: install_result is changed

# - name: download VMware.HV.Helper.psm1
#   win_get_url:
#     url: '{{ install_url_host }}\VMware.HV.Helper.psm1'
#     dest: 'C:\Program Files\WindowsPowerShell\Modules\VMware.HV.Helper\VMware.HV.Helper.psm1'
#   register: hv_result
#   when: install_result is changed

# - name: download VMware.HV.Helper.psd1
#   win_get_url:
#     url: '{{ install_url_host }}\VMware.HV.Helper.psd1'
#     dest: 'C:\Program Files\WindowsPowerShell\Modules\VMware.HV.Helper\VMware.HV.Helper.psd1'
#   register: hv_result2
#   when: install_result is changed

# - name: download VMware.HV.Helper.format.ps1xml
#   win_get_url:
#     url: '{{ install_url_host }}\VMware.HV.Helper.format.ps1xml'
#     dest: 'C:\Program Files\WindowsPowerShell\Modules\VMware.HV.Helper\VMware.HV.Helper.format.ps1xml'
#   register: hv_result3
#   when: install_result is changed

# - name: one time run of commands based on hv_result
#   win_shell: |
#     Set-PowerCLIConfiguration -Scope User -ParticipateInCeip:$false -Confirm:$false
#     Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false
#     Get-Command -Module 'VMware.HV.Helper'
#   when: 
#     - hv_result is changed
#     - hv_result2 is changed
#     - hv_result3 is changed

- include: connection_server_replica_upgrade.yml
